// Mock seed data – mirrors Prisma schema exactly
export const MOCK_COLLEGES = [
  {
    id: "1", name: "Indian Institute of Technology Bombay", shortName: "IIT Bombay",
    location: "Mumbai, Maharashtra", state: "Maharashtra", type: "Government",
    rating: 4.8, fees: 220000, established: 1958, ranking: 1,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 98, avgPackage: 2100000, highestPackage: 25000000,
    color: "#1a56c4", tags: ["Top Ranked", "IIT"],
    overview: "IIT Bombay is one of India's premier engineering institutions, consistently ranked in global top-200 lists. Established in 1958 with Soviet assistance, it offers cutting-edge research facilities, a vibrant startup ecosystem (with 300+ startups founded by alumni), and unmatched industry connections.",
  },
  {
    id: "2", name: "Indian Institute of Technology Delhi", shortName: "IIT Delhi",
    location: "New Delhi, Delhi", state: "Delhi", type: "Government",
    rating: 4.7, fees: 210000, established: 1961, ranking: 2,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 97, avgPackage: 1950000, highestPackage: 22000000,
    color: "#c41a1a", tags: ["Top Ranked", "IIT"],
    overview: "IIT Delhi, located in the heart of the capital, benefits from proximity to government, industry, and top MNCs. Its alumni network spans Fortune 500 companies globally, and its entrepreneurial ecosystem is among the strongest of any Indian technical institute.",
  },
  {
    id: "3", name: "Birla Institute of Technology and Science", shortName: "BITS Pilani",
    location: "Pilani, Rajasthan", state: "Rajasthan", type: "Deemed",
    rating: 4.5, fees: 480000, established: 1964, ranking: 12,
    courses: ["B.E.", "M.E.", "MBA", "PhD", "M.Sc"],
    streams: ["Engineering", "Science", "Management", "Pharmacy"],
    placementRate: 94, avgPackage: 1400000, highestPackage: 18000000,
    color: "#1a8c4e", tags: ["Private", "Top Private"],
    overview: "BITS Pilani pioneered the Practice School model that places students in real industry projects for months, giving graduates a decisive edge. Its dual-degree programs and no-entrance-barrier lateral transfer policy attract India's most ambitious students.",
  },
  {
    id: "4", name: "National Institute of Technology Trichy", shortName: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.4, fees: 150000, established: 1964, ranking: 8,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science"],
    placementRate: 92, avgPackage: 1100000, highestPackage: 12000000,
    color: "#7c1ac4", tags: ["NIT", "South India"],
    overview: "Consistently ranked #1 among National Institutes of Technology, NIT Trichy delivers IIT-comparable placements at a fraction of the cost. Its southern location makes it a hub for semiconductor, automotive, and software companies.",
  },
  {
    id: "5", name: "Vellore Institute of Technology", shortName: "VIT Vellore",
    location: "Vellore, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 4.1, fees: 390000, established: 1984, ranking: 15,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Science", "Management", "Computer Applications"],
    placementRate: 82, avgPackage: 650000, highestPackage: 8000000,
    color: "#c47a1a", tags: ["Private", "Large Campus"],
    overview: "VIT Vellore operates one of India's largest STEM campuses with 50,000+ students. Its Technology Business Incubator and strong MoUs with global universities make it a growing force in industry placements, particularly in IT services.",
  },
  {
    id: "6", name: "Indian Institute of Management Ahmedabad", shortName: "IIM Ahmedabad",
    location: "Ahmedabad, Gujarat", state: "Gujarat", type: "Government",
    rating: 4.9, fees: 2400000, established: 1961, ranking: 1,
    courses: ["MBA", "PGPX", "PhD", "Executive MBA"],
    streams: ["Management"],
    placementRate: 100, avgPackage: 3500000, highestPackage: 80000000,
    color: "#1a4c8c", tags: ["IIM", "Top MBA", "Management"],
    overview: "IIM Ahmedabad is India's most prestigious management school with a 100% placement record every year. Its case-method pedagogy, modeled on Harvard Business School, produces India's top CEOs, consultants, and policy makers.",
  },
  {
    id: "7", name: "Delhi Technological University", shortName: "DTU Delhi",
    location: "New Delhi, Delhi", state: "Delhi", type: "Government",
    rating: 4.0, fees: 175000, established: 1941, ranking: 22,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Management"],
    placementRate: 78, avgPackage: 780000, highestPackage: 7000000,
    color: "#1a7c8c", tags: ["Delhi", "Government"],
    overview: "DTU (formerly Delhi College of Engineering) is one of India's oldest engineering institutions. Its Delhi location attracts strong campus recruiters from IT, core engineering, and consulting sectors, and its fees remain affordable given government funding.",
  },
  {
    id: "8", name: "SRM Institute of Science and Technology", shortName: "SRM Chennai",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 3.8, fees: 340000, established: 1985, ranking: 35,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "BCA", "PhD"],
    streams: ["Engineering", "Science", "Management", "Computer Applications", "Arts"],
    placementRate: 70, avgPackage: 480000, highestPackage: 4500000,
    color: "#8c1a4c", tags: ["Private", "Large Intake", "South India"],
    overview: "SRM Institute is among India's largest private universities with a wide course catalog spanning engineering, medicine, law, and management. A large alumni base and active industry MoUs give students access to a broad recruiter pool.",
  },
 
  // ── Tamil Nadu additions ────────────────────────────────────────────
  {
    id: "9", name: "Indian Institute of Technology Madras", shortName: "IIT Madras",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.9, fees: 220000, established: 1959, ranking: 1,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc", "Dual Degree"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 97, avgPackage: 2300000, highestPackage: 36000000,
    color: "#1a3c2c", tags: ["Top Ranked", "IIT", "NIRF #1"],
    overview: "IIT Madras has topped India's NIRF overall rankings for several consecutive years. Its sprawling forested campus, India's most active research park, and the world's largest incubation cell (IIT Madras Incubation Cell) make it a magnet for deep-tech startups and research talent.",
  },
  {
    id: "10", name: "Anna University, College of Engineering Guindy", shortName: "CEG Anna University",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.2, fees: 65000, established: 1794, ranking: 28,
    courses: ["B.E.", "M.E.", "MBA", "M.Arch", "PhD"],
    streams: ["Engineering", "Science", "Management", "Architecture"],
    placementRate: 85, avgPackage: 720000, highestPackage: 4200000,
    color: "#4c1a8c", tags: ["Government", "Heritage", "Affordable"],
    overview: "One of Asia's oldest technical institutions, CEG is the flagship constituent college of Anna University. Rock-bottom government fees paired with a century-old alumni network across core engineering and public sector roles make it exceptional value.",
  },
  {
    id: "11", name: "PSG College of Technology", shortName: "PSG Tech",
    location: "Coimbatore, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.4, fees: 145000, established: 1951, ranking: 24,
    courses: ["B.E.", "B.Tech", "M.E.", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Science", "Management", "Computer Applications"],
    placementRate: 90, avgPackage: 850000, highestPackage: 5500000,
    color: "#c4a11a", tags: ["Autonomous", "South India", "Industry Ties"],
    overview: "PSG Tech is an autonomous institution renowned for its close ties to Coimbatore's manufacturing and textile industry, plus a fast-growing software placement track. Strong alumni presence in both core engineering and IT leadership roles.",
  },
  {
    id: "12", name: "Coimbatore Institute of Technology", shortName: "CIT Coimbatore",
    location: "Coimbatore, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.1, fees: 120000, established: 1956, ranking: 45,
    courses: ["B.E.", "M.E.", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Management", "Computer Applications"],
    placementRate: 82, avgPackage: 620000, highestPackage: 3800000,
    color: "#1ac4a1", tags: ["Autonomous", "Government-Aided"],
    overview: "CIT is a government-aided autonomous college with a strong reputation in core mechanical, production, and civil engineering, alongside a growing computer science placement record driven by Coimbatore's expanding IT corridor.",
  },
  {
    id: "13", name: "Thiagarajar College of Engineering", shortName: "TCE Madurai",
    location: "Madurai, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.0, fees: 110000, established: 1957, ranking: 52,
    courses: ["B.E.", "B.Tech", "M.E.", "MBA", "PhD"],
    streams: ["Engineering", "Management"],
    placementRate: 80, avgPackage: 580000, highestPackage: 3200000,
    color: "#8c4c1a", tags: ["Autonomous", "South Tamil Nadu"],
    overview: "TCE is the leading engineering institution in southern Tamil Nadu, government-aided and autonomous, with dedicated centres of excellence in robotics and renewable energy that feed direct industry partnerships.",
  },
  {
    id: "14", name: "Sri Sivasubramaniya Nadar College of Engineering", shortName: "SSN Chennai",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Private",
    rating: 4.2, fees: 195000, established: 1996, ranking: 40,
    courses: ["B.E.", "B.Tech", "M.E.", "MBA", "PhD"],
    streams: ["Engineering", "Management"],
    placementRate: 88, avgPackage: 780000, highestPackage: 4800000,
    color: "#2c1a4c", tags: ["Private", "Autonomous", "Strong CSE"],
    overview: "SSN is a self-financing autonomous college widely regarded as one of Tamil Nadu's best private engineering colleges outside the deemed-university tier, particularly for CSE and ECE placements into product companies.",
  },
  {
    id: "15", name: "Madras Institute of Technology, Anna University", shortName: "MIT Chennai",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.3, fees: 70000, established: 1949, ranking: 33,
    courses: ["B.Tech", "M.Tech", "PhD"],
    streams: ["Engineering", "Science"],
    placementRate: 86, avgPackage: 750000, highestPackage: 5000000,
    color: "#4c8c1a", tags: ["Government", "Anna University", "Aeronautics"],
    overview: "MIT Chennai, a constituent campus of Anna University, is India's pioneer in aeronautical, automobile, and instrumentation engineering, with graduates heavily recruited by aerospace, defence, and automotive R&D units.",
  },
  {
    id: "16", name: "Government College of Technology, Coimbatore", shortName: "GCT Coimbatore",
    location: "Coimbatore, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.0, fees: 55000, established: 1945, ranking: 58,
    courses: ["B.E.", "B.Tech", "M.E.", "MBA", "PhD"],
    streams: ["Engineering", "Management"],
    placementRate: 78, avgPackage: 550000, highestPackage: 3000000,
    color: "#c41a7c", tags: ["Government", "Anna University Autonomous"],
    overview: "GCT is one of the oldest government engineering colleges in Tamil Nadu, an Anna University autonomous institution known for rigorous core-engineering academics at government fee levels.",
  },
  {
    id: "17", name: "Kumaraguru College of Technology", shortName: "KCT Coimbatore",
    location: "Coimbatore, Tamil Nadu", state: "Tamil Nadu", type: "Private",
    rating: 3.9, fees: 175000, established: 1984, ranking: 60,
    courses: ["B.E.", "B.Tech", "M.E.", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Management", "Computer Applications"],
    placementRate: 75, avgPackage: 500000, highestPackage: 2800000,
    color: "#1a1a8c", tags: ["Private", "Autonomous"],
    overview: "KCT is a well-established autonomous private college in Coimbatore with a strong innovation and entrepreneurship cell that has spun off several student startups alongside a solid core placement pipeline.",
  },
  {
    id: "18", name: "Sathyabama Institute of Science and Technology", shortName: "Sathyabama Chennai",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 3.6, fees: 285000, established: 1987, ranking: 70,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Science", "Management", "Computer Applications"],
    placementRate: 68, avgPackage: 420000, highestPackage: 3500000,
    color: "#8c1a1a", tags: ["Deemed", "Large Campus"],
    overview: "Sathyabama is a large deemed university in Chennai with a diverse programme catalog spanning engineering, aeronautics, and biotechnology, plus its own student-built nanosatellite programme.",
  },
  {
    id: "19", name: "Hindustan Institute of Technology and Science", shortName: "Hindustan Chennai",
    location: "Kancheepuram, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 3.7, fees: 260000, established: 1985, ranking: 66,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 70, avgPackage: 450000, highestPackage: 3000000,
    color: "#1ac48c", tags: ["Deemed", "South Chennai"],
    overview: "Located on the Chennai–Kanyakumari corridor, Hindustan Institute is a deemed university with broad engineering and science offerings and steady placement links to IT services and manufacturing recruiters.",
  },
  {
    id: "20", name: "SASTRA Deemed University", shortName: "SASTRA Thanjavur",
    location: "Thanjavur, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 4.1, fees: 250000, established: 1984, ranking: 30,
    courses: ["B.Tech", "M.Tech", "MBA", "M.Sc", "PhD", "Pharm.D"],
    streams: ["Engineering", "Science", "Management", "Pharmacy"],
    placementRate: 85, avgPackage: 680000, highestPackage: 4400000,
    color: "#a11ac4", tags: ["Deemed", "NIRF Ranked", "Research"],
    overview: "SASTRA has climbed steadily in NIRF rankings, combining a research-driven deemed-university model with consistently strong placement rates for a mid-sized private institution, particularly in core and software engineering.",
  },
  {
    id: "21", name: "Karunya Institute of Technology and Sciences", shortName: "Karunya Coimbatore",
    location: "Coimbatore, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 3.8, fees: 210000, established: 1986, ranking: 62,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 72, avgPackage: 460000, highestPackage: 3100000,
    color: "#4c1a1a", tags: ["Deemed", "Green Campus"],
    overview: "Karunya is a deemed university on a scenic Coimbatore hill campus, known for aerospace and agricultural engineering programmes alongside mainstream CSE/ECE tracks and an active research grant portfolio.",
  },
  {
    id: "22", name: "Kalasalingam Academy of Research and Education", shortName: "Kalasalingam Krishnankoil",
    location: "Krishnankoil, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 3.7, fees: 190000, established: 1984, ranking: 68,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 70, avgPackage: 400000, highestPackage: 2600000,
    color: "#1a4c1a", tags: ["Deemed", "South Tamil Nadu"],
    overview: "Kalasalingam is a deemed university serving southern Tamil Nadu's Virudhunagar–Madurai belt, offering affordable-for-deemed fees with a growing focus on AI, data science, and cybersecurity specializations.",
  },
  {
    id: "23", name: "Christian Medical College, Vellore", shortName: "CMC Vellore",
    location: "Vellore, Tamil Nadu", state: "Tamil Nadu", type: "Private",
    rating: 4.8, fees: 65000, established: 1900, ranking: 2,
    courses: ["MBBS", "MD", "MS", "B.Sc Nursing", "PhD"],
    streams: ["Medical"],
    placementRate: 100, avgPackage: 1200000, highestPackage: 4000000,
    color: "#7c8c1a", tags: ["Top Medical", "Historic", "NIRF Ranked"],
    overview: "CMC Vellore is consistently ranked among India's top two medical colleges, combining over a century of clinical excellence with a mission-driven rural service ethos and an intensely competitive admissions process.",
  },
  {
    id: "24", name: "Loyola College, Chennai", shortName: "Loyola Chennai",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Private",
    rating: 4.3, fees: 35000, established: 1925, ranking: 20,
    courses: ["B.A.", "B.Sc", "B.Com", "M.A.", "M.Sc", "PhD"],
    streams: ["Arts", "Science", "Commerce"],
    placementRate: 80, avgPackage: 480000, highestPackage: 2500000,
    color: "#1a7cc4", tags: ["Autonomous", "Arts & Science", "Heritage"],
    overview: "Loyola College is one of India's top-ranked autonomous arts and science colleges, celebrated for its economics, commerce, and social sciences departments and a placement cell that draws consulting and BFSI recruiters.",
  },
 
  // ── Other India additions ───────────────────────────────────────────
  {
    id: "25", name: "Indian Institute of Technology Kanpur", shortName: "IIT Kanpur",
    location: "Kanpur, Uttar Pradesh", state: "Uttar Pradesh", type: "Government",
    rating: 4.8, fees: 220000, established: 1959, ranking: 4,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 96, avgPackage: 2000000, highestPackage: 21000000,
    color: "#2c4c1a", tags: ["Top Ranked", "IIT"],
    overview: "IIT Kanpur pioneered computer science education in India and remains a top destination for CS and aerospace research, with a large on-campus airstrip and one of the country's earliest startup incubators.",
  },
  {
    id: "26", name: "Indian Institute of Technology Kharagpur", shortName: "IIT Kharagpur",
    location: "Kharagpur, West Bengal", state: "West Bengal", type: "Government",
    rating: 4.7, fees: 220000, established: 1951, ranking: 5,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc", "Dual Degree"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 95, avgPackage: 1900000, highestPackage: 20000000,
    color: "#8c2c1a", tags: ["Top Ranked", "IIT", "Largest Campus"],
    overview: "India's first IIT, Kharagpur has the country's largest academic campus and a broad department spread from ocean engineering to law, giving it one of the widest recruiter bases of any IIT.",
  },
  {
    id: "27", name: "Indian Institute of Technology Roorkee", shortName: "IIT Roorkee",
    location: "Roorkee, Uttarakhand", state: "Uttarakhand", type: "Government",
    rating: 4.5, fees: 220000, established: 1847, ranking: 6,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 93, avgPackage: 1750000, highestPackage: 18000000,
    color: "#1a2c8c", tags: ["IIT", "Heritage"],
    overview: "Originally founded in 1847 as one of Asia's oldest engineering colleges, IIT Roorkee is especially strong in civil, water resources, and earthquake engineering, alongside a fast-rising CSE placement track.",
  },
  {
    id: "28", name: "Indian Institute of Science", shortName: "IISc Bangalore",
    location: "Bengaluru, Karnataka", state: "Karnataka", type: "Government",
    rating: 4.9, fees: 60000, established: 1909, ranking: 1,
    courses: ["B.S.", "M.Tech", "M.Sc", "PhD", "Integrated PhD"],
    streams: ["Engineering", "Science"],
    placementRate: 90, avgPackage: 1800000, highestPackage: 15000000,
    color: "#4c8c8c", tags: ["Top Ranked", "Research", "NIRF #1 University"],
    overview: "IISc is India's top-ranked research university and a global leader in fundamental sciences, aerospace, and materials research, drawing the country's most research-oriented undergraduates and PhD candidates.",
  },
  {
    id: "29", name: "National Institute of Technology Warangal", shortName: "NIT Warangal",
    location: "Warangal, Telangana", state: "Telangana", type: "Government",
    rating: 4.3, fees: 155000, established: 1959, ranking: 10,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 90, avgPackage: 1050000, highestPackage: 11000000,
    color: "#8c4c4c", tags: ["NIT", "South India"],
    overview: "NIT Warangal, one of the oldest and highest-ranked NITs, has a strong core-engineering legacy alongside a growing computer science placement pipeline into top product and services companies.",
  },
  {
    id: "30", name: "National Institute of Technology Karnataka, Surathkal", shortName: "NITK Surathkal",
    location: "Mangaluru, Karnataka", state: "Karnataka", type: "Government",
    rating: 4.3, fees: 155000, established: 1960, ranking: 11,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 89, avgPackage: 1020000, highestPackage: 10500000,
    color: "#1a8c2c", tags: ["NIT", "Beachside Campus"],
    overview: "NITK Surathkal, on a coastal Karnataka campus, is consistently among the top three NITs nationally, with especially strong information technology and electronics placement outcomes.",
  },
  {
    id: "31", name: "Indian Institute of Management Bangalore", shortName: "IIM Bangalore",
    location: "Bengaluru, Karnataka", state: "Karnataka", type: "Government",
    rating: 4.8, fees: 2450000, established: 1973, ranking: 2,
    courses: ["MBA", "PGP", "PhD", "Executive MBA"],
    streams: ["Management"],
    placementRate: 100, avgPackage: 3400000, highestPackage: 75000000,
    color: "#4c1a4c", tags: ["IIM", "Top MBA"],
    overview: "IIM Bangalore is India's top-rated business school by GMAC and NIRF surveys in several recent years, known for its strong entrepreneurship and consulting placement tracks and proximity to India's startup capital.",
  },
  {
    id: "32", name: "Indian Institute of Management Calcutta", shortName: "IIM Calcutta",
    location: "Kolkata, West Bengal", state: "West Bengal", type: "Government",
    rating: 4.8, fees: 2700000, established: 1961, ranking: 3,
    courses: ["MBA", "PGDM", "PhD", "Executive MBA"],
    streams: ["Management"],
    placementRate: 100, avgPackage: 3300000, highestPackage: 70000000,
    color: "#8c1a2c", tags: ["IIM", "Top MBA", "Oldest IIM"],
    overview: "India's oldest IIM, Calcutta is renowned for finance placements into global investment banks and consulting firms, and runs India's first internationally accredited MBA-equivalent programme.",
  },
  {
    id: "33", name: "All India Institute of Medical Sciences, Delhi", shortName: "AIIMS Delhi",
    location: "New Delhi, Delhi", state: "Delhi", type: "Government",
    rating: 4.9, fees: 6000, established: 1956, ranking: 1,
    courses: ["MBBS", "MD", "MS", "B.Sc Nursing", "PhD"],
    streams: ["Medical"],
    placementRate: 100, avgPackage: 1400000, highestPackage: 5000000,
    color: "#2c8c4c", tags: ["Top Medical", "NIRF #1 Medical"],
    overview: "AIIMS Delhi is India's top-ranked medical institution nearly every year, offering government-subsidized fees, world-class clinical exposure, and the country's most competitive medical entrance cutoffs.",
  },
  {
    id: "34", name: "Jadavpur University", shortName: "Jadavpur University",
    location: "Kolkata, West Bengal", state: "West Bengal", type: "Government",
    rating: 4.3, fees: 15000, established: 1955, ranking: 18,
    courses: ["B.E.", "M.E.", "B.A.", "M.A.", "PhD"],
    streams: ["Engineering", "Science", "Arts"],
    placementRate: 84, avgPackage: 700000, highestPackage: 4500000,
    color: "#1a4c4c", tags: ["Government", "Ultra-Affordable", "Heritage"],
    overview: "Jadavpur University offers some of India's lowest engineering fees at a public university while consistently ranking among the country's top general universities in NIRF, spanning both engineering and humanities.",
  },
  {
    id: "35", name: "Manipal Institute of Technology", shortName: "MIT Manipal",
    location: "Manipal, Karnataka", state: "Karnataka", type: "Deemed",
    rating: 3.9, fees: 440000, established: 1957, ranking: 46,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 78, avgPackage: 620000, highestPackage: 5200000,
    color: "#4c2c8c", tags: ["Deemed", "Large Campus", "International"],
    overview: "MIT Manipal, part of Manipal Academy of Higher Education, draws a large international student body and offers strong industry tie-ups in automotive, aerospace, and IT, on a self-contained university town campus.",
  },
  {
    id: "36", name: "Symbiosis Institute of Technology", shortName: "SIT Pune",
    location: "Pune, Maharashtra", state: "Maharashtra", type: "Private",
    rating: 3.8, fees: 320000, established: 2008, ranking: 55,
    courses: ["B.Tech", "M.Tech", "MBA"],
    streams: ["Engineering", "Management"],
    placementRate: 76, avgPackage: 560000, highestPackage: 3200000,
    color: "#8c4c2c", tags: ["Private", "Pune"],
    overview: "Part of the well-known Symbiosis group, SIT Pune combines a relatively young engineering programme with the group's strong corporate placement network built primarily around its flagship management institutes.",
  },
  {
    id: "37", name: "Shri Ram College of Commerce", shortName: "SRCC Delhi",
    location: "New Delhi, Delhi", state: "Delhi", type: "Government",
    rating: 4.6, fees: 20000, established: 1926, ranking: 3,
    courses: ["B.Com", "B.A. Economics", "M.A."],
    streams: ["Commerce", "Arts"],
    placementRate: 92, avgPackage: 900000, highestPackage: 6000000,
    color: "#c48c1a", tags: ["Top Commerce", "Delhi University", "Heritage"],
    overview: "SRCC is India's most sought-after commerce and economics college under Delhi University, feeding graduates directly into top investment banks, consulting firms, and civil services with minimal government fees.",
  },
];
 
export const MOCK_REVIEWS = [
  { id: "r1", collegeId: "1", userId: "u1", rating: 5, text: "Best technical education in India. Faculty is world-class and the research opportunities are unmatched.", user: { name: "Rahul M." }, createdAt: "2024-03-01" },
  { id: "r2", collegeId: "1", userId: "u2", rating: 5, text: "Incredible campus life. The peer group here is the most driven I've ever encountered.", user: { name: "Priya S." }, createdAt: "2024-01-15" },
  { id: "r3", collegeId: "2", userId: "u3", rating: 5, text: "Great infrastructure and unparalleled industry exposure being in Delhi.", user: { name: "Ankit K." }, createdAt: "2024-02-20" },
  { id: "r4", collegeId: "2", userId: "u4", rating: 4, text: "Strong alumni network opens many doors. Research funding could be better though.", user: { name: "Sneha R." }, createdAt: "2023-12-10" },
  { id: "r5", collegeId: "3", userId: "u5", rating: 5, text: "Practice School is a game-changer. I had 2 full-time internship experiences before graduating.", user: { name: "Vikram T." }, createdAt: "2024-01-05" },
  { id: "r6", collegeId: "4", userId: "u6", rating: 4, text: "Best NIT in India. Placement numbers speak for themselves.", user: { name: "Arun P." }, createdAt: "2024-02-14" },
  { id: "r7", collegeId: "5", userId: "u7", rating: 4, text: "Amazing campus facilities and tech fest. Placement varies a lot by branch.", user: { name: "Rohan B." }, createdAt: "2024-01-22" },
  { id: "r8", collegeId: "6", userId: "u8", rating: 5, text: "Life-changing two years. Peer learning is 60% of the value here.", user: { name: "Suresh N." }, createdAt: "2024-03-10" },
];
 
export const MOCK_QUESTIONS = [
  {
    id: "q1", collegeId: "1", userId: "u9", upvotes: 31,
    question: "What is the JEE Advanced cutoff for CSE at IIT Bombay for general category?",
    user: { name: "JEE2024" }, createdAt: "2024-03-05",
    answers: [{ id: "a1", userId: "u1", text: "General category rank should be within 80–130 for CSE. It fluctuates ±30 each year depending on difficulty and student count.", upvotes: 24, user: { name: "IITBAlumni" }, createdAt: "2024-03-06" }],
  },
  {
    id: "q2", collegeId: "2", userId: "u10", upvotes: 22,
    question: "Is hostel accommodation guaranteed for all B.Tech students at IIT Delhi?",
    user: { name: "Aspirant2025" }, createdAt: "2024-02-10",
    answers: [{ id: "a2", userId: "u3", text: "Yes, hostel is mandatory and guaranteed for all first-year students. After that it depends on availability via lottery.", upvotes: 18, user: { name: "IITDStudent" }, createdAt: "2024-02-11" }],
  },
  {
    id: "q3", collegeId: null, userId: "u11", upvotes: 58,
    question: "Which is better for CSE – NIT Trichy or VIT Vellore? Purely from placements POV.",
    user: { name: "CollegeSeeker" }, createdAt: "2024-01-20",
    answers: [{ id: "a3", userId: "u6", text: "NIT Trichy is significantly better for placements and brand value for CSE. VIT has better infrastructure and campus life, but NIT brand opens more doors.", upvotes: 45, user: { name: "BothApplicant" }, createdAt: "2024-01-21" }],
  },
  {
    id: "q4", collegeId: "3", userId: "u12", upvotes: 40,
    question: "How valuable is the dual-degree (integrated) program at BITS Pilani vs single degree?",
    user: { name: "BITSAspirant" }, createdAt: "2023-12-15",
    answers: [{ id: "a4", userId: "u5", text: "Dual degree gives you both B.E. and M.Sc. in 5 years. Excellent for research roles or PhD abroad. For immediate industry jobs, single degree is faster.", upvotes: 30, user: { name: "BITSian" }, createdAt: "2023-12-16" }],
  },
];
