// Mock seed data – mirrors Prisma schema exactly
export const MOCK_COLLEGES = [
  {
    id: "1", name: "Indian Institute of Technology Bombay", shortName: "IIT Bombay",
    location: "Mumbai, Maharashtra", state: "Maharashtra", type: "Government",
    rating: 4.8, fees: 220000, established: 1958, ranking: 1,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 98, avgPackage: 2100000, highestPackage: 25000000,
    color: "#1a56c4", tags: ["Top Ranked", "IIT"],
    overview: "IIT Bombay is one of India's premier engineering institutions, consistently ranked in global top-200 lists. Established in 1958 with Soviet assistance, it offers cutting-edge research facilities, a vibrant startup ecosystem (with 300+ startups founded by alumni), and unmatched industry connections.",
  },
  {
    id: "2", name: "Indian Institute of Technology Delhi", shortName: "IIT Delhi",
    location: "New Delhi, Delhi", state: "Delhi", type: "Government",
    rating: 4.7, fees: 210000, established: 1961, ranking: 2,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science", "Management"],
    placementRate: 97, avgPackage: 1950000, highestPackage: 22000000,
    color: "#c41a1a", tags: ["Top Ranked", "IIT"],
    overview: "IIT Delhi, located in the heart of the capital, benefits from proximity to government, industry, and top MNCs. Its alumni network spans Fortune 500 companies globally, and its entrepreneurial ecosystem is among the strongest of any Indian technical institute.",
  },
  {
    id: "3", name: "Birla Institute of Technology and Science", shortName: "BITS Pilani",
    location: "Pilani, Rajasthan", state: "Rajasthan", type: "Deemed",
    rating: 4.5, fees: 480000, established: 1964, ranking: 12,
    courses: ["B.E.", "M.E.", "MBA", "PhD", "M.Sc"],
    streams: ["Engineering", "Science", "Management", "Pharmacy"],
    placementRate: 94, avgPackage: 1400000, highestPackage: 18000000,
    color: "#1a8c4e", tags: ["Private", "Top Private"],
    overview: "BITS Pilani pioneered the Practice School model that places students in real industry projects for months, giving graduates a decisive edge. Its dual-degree programs and no-entrance-barrier lateral transfer policy attract India's most ambitious students.",
  },
  {
    id: "4", name: "National Institute of Technology Trichy", shortName: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu", state: "Tamil Nadu", type: "Government",
    rating: 4.4, fees: 150000, established: 1964, ranking: 8,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Science"],
    placementRate: 92, avgPackage: 1100000, highestPackage: 12000000,
    color: "#7c1ac4", tags: ["NIT", "South India"],
    overview: "Consistently ranked #1 among National Institutes of Technology, NIT Trichy delivers IIT-comparable placements at a fraction of the cost. Its southern location makes it a hub for semiconductor, automotive, and software companies.",
  },
  {
    id: "5", name: "Vellore Institute of Technology", shortName: "VIT Vellore",
    location: "Vellore, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 4.1, fees: 390000, established: 1984, ranking: 15,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    streams: ["Engineering", "Science", "Management", "Computer Applications"],
    placementRate: 82, avgPackage: 650000, highestPackage: 8000000,
    color: "#c47a1a", tags: ["Private", "Large Campus"],
    overview: "VIT Vellore operates one of India's largest STEM campuses with 50,000+ students. Its Technology Business Incubator and strong MoUs with global universities make it a growing force in industry placements, particularly in IT services.",
  },
  {
    id: "6", name: "Indian Institute of Management Ahmedabad", shortName: "IIM Ahmedabad",
    location: "Ahmedabad, Gujarat", state: "Gujarat", type: "Government",
    rating: 4.9, fees: 2400000, established: 1961, ranking: 1,
    courses: ["MBA", "PGPX", "PhD", "Executive MBA"],
    streams: ["Management"],
    placementRate: 100, avgPackage: 3500000, highestPackage: 80000000,
    color: "#1a4c8c", tags: ["IIM", "Top MBA", "Management"],
    overview: "IIM Ahmedabad is India's most prestigious management school with a 100% placement record every year. Its case-method pedagogy, modeled on Harvard Business School, produces India's top CEOs, consultants, and policy makers.",
  },
  {
    id: "7", name: "Delhi Technological University", shortName: "DTU Delhi",
    location: "New Delhi, Delhi", state: "Delhi", type: "Government",
    rating: 4.0, fees: 175000, established: 1941, ranking: 22,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    streams: ["Engineering", "Management"],
    placementRate: 78, avgPackage: 780000, highestPackage: 7000000,
    color: "#1a7c8c", tags: ["Delhi", "Government"],
    overview: "DTU (formerly Delhi College of Engineering) is one of India's oldest engineering institutions. Its Delhi location attracts strong campus recruiters from IT, core engineering, and consulting sectors, and its fees remain affordable given government funding.",
  },
  {
    id: "8", name: "SRM Institute of Science and Technology", shortName: "SRM Chennai",
    location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "Deemed",
    rating: 3.8, fees: 340000, established: 1985, ranking: 35,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "BCA", "PhD"],
    streams: ["Engineering", "Science", "Management", "Computer Applications", "Arts"],
    placementRate: 70, avgPackage: 480000, highestPackage: 4500000,
    color: "#8c1a4c", tags: ["Private", "Large Intake", "South India"],
    overview: "SRM Institute is among India's largest private universities with a wide course catalog spanning engineering, medicine, law, and management. A large alumni base and active industry MoUs give students access to a broad recruiter pool.",
  },
];

export const MOCK_REVIEWS = [
  { id: "r1", collegeId: "1", userId: "u1", rating: 5, text: "Best technical education in India. Faculty is world-class and the research opportunities are unmatched.", user: { name: "Rahul M." }, createdAt: "2024-03-01" },
  { id: "r2", collegeId: "1", userId: "u2", rating: 5, text: "Incredible campus life. The peer group here is the most driven I've ever encountered.", user: { name: "Priya S." }, createdAt: "2024-01-15" },
  { id: "r3", collegeId: "2", userId: "u3", rating: 5, text: "Great infrastructure and unparalleled industry exposure being in Delhi.", user: { name: "Ankit K." }, createdAt: "2024-02-20" },
  { id: "r4", collegeId: "2", userId: "u4", rating: 4, text: "Strong alumni network opens many doors. Research funding could be better though.", user: { name: "Sneha R." }, createdAt: "2023-12-10" },
  { id: "r5", collegeId: "3", userId: "u5", rating: 5, text: "Practice School is a game-changer. I had 2 full-time internship experiences before graduating.", user: { name: "Vikram T." }, createdAt: "2024-01-05" },
  { id: "r6", collegeId: "4", userId: "u6", rating: 4, text: "Best NIT in India. Placement numbers speak for themselves.", user: { name: "Arun P." }, createdAt: "2024-02-14" },
  { id: "r7", collegeId: "5", userId: "u7", rating: 4, text: "Amazing campus facilities and tech fest. Placement varies a lot by branch.", user: { name: "Rohan B." }, createdAt: "2024-01-22" },
  { id: "r8", collegeId: "6", userId: "u8", rating: 5, text: "Life-changing two years. Peer learning is 60% of the value here.", user: { name: "Suresh N." }, createdAt: "2024-03-10" },
];

export const MOCK_QUESTIONS = [
  {
    id: "q1", collegeId: "1", userId: "u9", upvotes: 31,
    question: "What is the JEE Advanced cutoff for CSE at IIT Bombay for general category?",
    user: { name: "JEE2024" }, createdAt: "2024-03-05",
    answers: [{ id: "a1", userId: "u1", text: "General category rank should be within 80–130 for CSE. It fluctuates ±30 each year depending on difficulty and student count.", upvotes: 24, user: { name: "IITBAlumni" }, createdAt: "2024-03-06" }],
  },
  {
    id: "q2", collegeId: "2", userId: "u10", upvotes: 22,
    question: "Is hostel accommodation guaranteed for all B.Tech students at IIT Delhi?",
    user: { name: "Aspirant2025" }, createdAt: "2024-02-10",
    answers: [{ id: "a2", userId: "u3", text: "Yes, hostel is mandatory and guaranteed for all first-year students. After that it depends on availability via lottery.", upvotes: 18, user: { name: "IITDStudent" }, createdAt: "2024-02-11" }],
  },
  {
    id: "q3", collegeId: null, userId: "u11", upvotes: 58,
    question: "Which is better for CSE – NIT Trichy or VIT Vellore? Purely from placements POV.",
    user: { name: "CollegeSeeker" }, createdAt: "2024-01-20",
    answers: [{ id: "a3", userId: "u6", text: "NIT Trichy is significantly better for placements and brand value for CSE. VIT has better infrastructure and campus life, but NIT brand opens more doors.", upvotes: 45, user: { name: "BothApplicant" }, createdAt: "2024-01-21" }],
  },
  {
    id: "q4", collegeId: "3", userId: "u12", upvotes: 40,
    question: "How valuable is the dual-degree (integrated) program at BITS Pilani vs single degree?",
    user: { name: "BITSAspirant" }, createdAt: "2023-12-15",
    answers: [{ id: "a4", userId: "u5", text: "Dual degree gives you both B.E. and M.Sc. in 5 years. Excellent for research roles or PhD abroad. For immediate industry jobs, single degree is faster.", upvotes: 30, user: { name: "BITSian" }, createdAt: "2023-12-16" }],
  },
];
